name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Bootstrap dependencies
      run: npm ci
    - name: Ensure project can be built
      run: npm run-script build
    - name: Run linters
      run: npm run-script verify
    - name: Run Sonar
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=qlba
          -Dsonar.projectKey=xlam
          -Dsonar.javascript.lcov.reportPaths=${{ github.workspace }}/coverage/lcov.info
    - name: Upload coverage to Code Climate
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: fc93a1841ed3b2d045f96fac98dee4fb8c8a4010ce2a984bd1cc792edae01492
      with:
        # Coverage command to execute
        coverageCommand: npm run-script verify-jest
        # Locations to find code coverage (Used for builds from multiple locations)
        coverageLocations: |
          ${{ github.workspace }}/coverage/lcov.info:lcov
