# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run-script verify
    - name: Code Climate Coverage Action
      # You may pin to the exact commit or the version.
      # uses: paambaati/codeclimate-action@84cea27117a473d605400ca3a97fcef7e433e2d6
      uses: paambaati/codeclimate-action@v3.0.0
      with:
        # Coverage command to execute
        coverageCommand: npm run-script verify-jest
        # Custom working directory for executing the coverage command
        workingDirectory: .
        # Enable debugging logs for the Code Climate test reporter
        debug: false
        # Locations to find code coverage (Used for builds from multiple locations)
        coverageLocations: src/
        # See https://docs.codeclimate.com/docs/configuring-test-coverage
        prefix: ./
        # Verify the downloaded reporter's checksum and GPG signature
        verifyDownload: true
